### PR TITLE
docs: move terraform to configure part

### PR DESCRIPTION
**Pull request by adela-bytebase**
We're using terraform to configure workspace-level environment/instance/role. So the doc would better belong to 'Configure  Workspace' Section.

### CODE REVIEW

**Comment by tianzhou** [comment]
This is intentional:

1. We want to highlight terraform integration, so it's shown by default
CleanShot 2022-11-29 at 17 36 01

2. Terraform can configure many aspects of Bytebase. So strickly speaking, it's not at the same level as other items under configure/, since those items just configure one feature.

**Comment by adela-bytebase** [comment]
> This is intentional:
> 
> 1. We want to highlight terraform integration, so it's shown by default
>    CleanShot 2022-11-29 at 17 36 01
> 2. Terraform can configure many aspects of Bytebase. So strickly speaking, it's not at the same level as other items under configure/, since those items just configure one feature.

Got it! Maybe we can replace "work with" with some other words, or it might be misleading - "work with project" and "work with terraform" look similar.

**Comment by tianzhou** [comment]
> > This is intentional:
> > 
> > 1. We want to highlight terraform integration, so it's shown by default
> >    CleanShot 2022-11-29 at 17 36 01
> > 2. Terraform can configure many aspects of Bytebase. So strickly speaking, it's not at the same level as other items under configure/, since those items just configure one feature.
> 
> Got it! Maybe we can replace "work with" with some other words, or it might be misleading - "work with project" and "work with terraform" look similar.

Let's call it `Manage with Terraform` and make the URL just `/terraform`

Because the full sentence is "Manage Bytebase with Terraform"

**Review by tianzhou — CHANGES_REQUESTED** [review]
Let's call it `Manage with Terraform` and make the URL just `/terraform`

Because the full sentence is "Manage Bytebase with Terraform"

**Comment by tianzhou** [comment]
And for "Work with a Project", how about changing it to "Configure Project"?

**Comment by candy2255** [comment]
How about moving it to "How to - Integrations"?
CleanShot 2022-11-30 at 07 46 07@2x

**Comment by adela-bytebase** [comment]
> And for "Work with a Project", how about changing it to "Configure Project"?

It's not only about "configure" but also includes "run an issue".

**Comment by adela-bytebase** [comment]
> How about moving it to "How to - Integrations"? CleanShot 2022-11-30 at 07 46 07@2x

Cuz we want to highlight this way of configuration, it'd better stay in the main doc.

**Review by tianzhou — APPROVED** [review]
LGTM

**Pull request merged**
