### PR TITLE
chore: update for saas

### PR DESCRIPTION
**Pull request by ecmadao**
CleanShot 2023-03-16 at 13 56 01@2x
CleanShot 2023-03-16 at 13 56 10@2x

Close BYT-2777

DO NOT merge this PR till the hub is released

### CODE REVIEW

**Review by tianzhou — APPROVED** [review]
LGTM

**Comment by boojack** [comment]
The header is overflow in mobile view.

image

**Review by Candybase — APPROVED** [review]
LGTM

**Comment by ecmadao** [comment]
> The header is overflow in mobile view.
> 
> image

Hide the "Self Host" button in small screen now @boojack

**Review by boojack — APPROVED** [review]
LGTM

**Pull request merged**
