### PR TITLE
feat: add author avator and name in changelog

### PR DESCRIPTION
**Pull request by ecmadao**
图片

图片

CleanShot 2022-03-04 at 15 08 55

### CODE REVIEW

**Review by tianzhou — COMMENTED** [review]
How about putting the profile info below the title>

Originally thought is to reserve the clicking area exclusively for the deploy button.

wdyt?

**Comment by ecmadao** [comment]
If we just wanna show the author, maybe put it under the title like just like the blog list page?

CleanShot 2022-03-05 at 11 24 36

but with an entry to all articles from this author.

**Comment by tianzhou** [comment]
> If we just wanna show the author, maybe put it under the title like just like the blog list page?
> 
> CleanShot 2022-03-05 at 11 24 36
> 
> but with an entry to all articles from this author.

SGTM

**Review by tianzhou — APPROVED** [review]
LGTM

**Pull request merged**
