### PR TITLE
chore: optimize pricing and fix segment error in SSR

### PR DESCRIPTION
**Pull request by ecmadao**
- Optimize the pricing
图片
图片

- Fix the segment init error in SSR (the window will be undefined in SSR)
图片

### CODE REVIEW

**Comment by ecmadao** [comment]
> Maybe we can use `watch` in setup instead of `watchEffect` in onMounted. https://stackoverflow.com/a/69279786

I guess you meant to use the watch

```
setup() {
 watch(
      () => useSegment().analytics,
      (segment) => {
        segment?.page(route.value.name);
      }
    );
}
```

in this way?

but this cannot resolve the problem. I put the `watchEffect` inside the `onMounted` to avoid the segment initial error in SSR mode.

**Review by boojack — DISMISSED** [review]
LGTM. `nuxt2` looks so weird;)

**Comment by ecmadao** [comment]
The UI for pricing is updated, PTAL @tianzhou

**Review by boojack — APPROVED** [review]
LGTM

**Review by d-bytebase — APPROVED** [review]

**Pull request merged**
