### PR TITLE
chore: update chinese text line height

### PR DESCRIPTION
**Pull request by boojack**

### CODE REVIEW

**Review by tianzhou — COMMENTED** [review]
Let's see if we can use font family to apply a global setting

**Comment by boojack** [comment]
@tianzhou We cannot set custom style(line-height...) for font family. So we still need to override the `line-height` in Chinese locale by detecting locale changes.

And I use a global css to override the TailwindCSS default `line-height` for large font size from `1` to `1.15` only in Chinese locale.

**Review by tianzhou — APPROVED** [review]
LGTM

**Comment by tianzhou** [comment]
TIL

**Pull request merged**
