### PR TITLE
chore: use cookie to store the url parameters

### PR DESCRIPTION
**Pull request by ecmadao**
Synced with @tianzhou , we can use cookies to store the URL parameters.

### CODE REVIEW

**Review by boojack — APPROVED** [review]
LGTM

---

As nuxt router/link bases on vue-router, so I think we can handle the query params in a vue-router way.
* https://github.com/vuejs/vue-router/issues/1631#issuecomment-527922069

**Review by d-bytebase — DISMISSED** [review]

**Comment by ecmadao** [comment]
Code updated. We will use cookies to store the URL parameters. PTAL @boojack @d-bytebase @tianzhou

**Review by boojack — APPROVED** [review]
LGTM

**Review by tianzhou — APPROVED** [review]
LGTM

**Pull request merged**
