### PR TITLE
chore: root section foldable

### PR DESCRIPTION
**Pull request by boojack**
image

### CODE REVIEW

**Review by tianzhou — COMMENTED** [review]
How about supporting to toggle the expandable state by clicking the title as well?

**Comment by boojack** [comment]
> How about supporting to toggle the expandable state by clicking the title as well?

Sorry for forgetting this. And this has been added.

**Comment by tianzhou** [comment]
Let's use the hand cursor when mouse hovers the title?

**Review by tianzhou — APPROVED** [review]
LGTM

**Review by d-bytebase — APPROVED** [review]

**Pull request merged**
