### PR TITLE
docs: tweak Terraform doc

### PR DESCRIPTION
**Pull request by tianzhou**
Make it more succinct.

### CODE REVIEW

**Comment by tianzhou** [comment]
@ecmadao I am also thinking of renaming bytebase_url to url, and point it to external_url instead of external_url/v1. The reason is to avoid exposing another endpoint.

Since the provider itself is versioned already, thus there is no need to expose the API version. Say TF provider 1.0 works with our /v1, TF provider 2.0 works with our /v2.

Thoughts?

**Comment by tianzhou** [comment]
As for the naming, HashiCorp own products use `address`, and I see some other products use `endpoint`. I propose url because it correlates with "external_url"

**Comment by ecmadao** [comment]
> @ecmadao I am also thinking of renaming bytebase_url to url, and point it to external_url instead of external_url/v1. The reason is to avoid exposing another endpoint.
> 
> Since the provider itself is versioned already, thus there is no need to expose the API version. Say TF provider 1.0 works with our /v1, TF provider 2.0 works with our /v2.
> 
> Thoughts?

LGTM. Let me update the provider in next version

**Review by ecmadao — APPROVED** [review]
LGTM

**Pull request merged**
