### PR TITLE
docs: update the gif and docs in sql review

### PR DESCRIPTION
**Pull request by rebelice**
- update the gif in SQL review
- refactor the docs in SQL review
- add PostgreSQL supported rule information

Hint: The only content that needs to review is the `PRIMARY KEY NAMING CONVENTION`. For other rules, I just move them to one single file.

### CODE REVIEW

**Comment by tianzhou** [comment]
Not translated

CleanShot 2022-08-04 at 16 24 21

**Review by tianzhou — CHANGES_REQUESTED** [review]
Not translated

CleanShot 2022-08-04 at 16 24 21

**Comment by rebelice** [comment]
Updated. PTAL @tianzhou

**Review by tianzhou — APPROVED** [review]
LGTM

**Pull request merged**
