### PR TITLE
feat: add header metadata for blog pages

### PR DESCRIPTION
**Pull request by boojack**
* Add header metadata for blog pages;
* Use `background-image` instead of `img` element to hide `star us` image when sharing in wechat;
* Fix banner styles in mobile view;

### CODE REVIEW

**Review by tianzhou — DISMISSED** [review]
LGTM

**Review by ecmadao — COMMENTED** [review]
Also remove the unused `starus.png` in assets folder? LGTM otherwise.

**Comment by boojack** [comment]
PTAL

**Review by ecmadao — APPROVED** [review]
LGTM

**Pull request merged**
