### PR TITLE
add candy to team page

### PR DESCRIPTION
**Pull request by candy2255**
add candy to team page

### CODE REVIEW

**Comment by d-bytebase** [comment]
Also need to add candy.webp

**Comment by candy2255** [comment]
> Also need to add candy.webp
上传了，上传 webp 和 修改 code 分开提交的

webp commit:https://github.com/bytebase/bytebase.com/pull/144/commits

**Comment by d-bytebase** [comment]
> Also need to add candy.webp

nvm, just saw https://github.com/bytebase/bytebase.com/pull/144. Should be part of same change/PR.

**Review by d-bytebase — APPROVED** [review]
Welcome aboard!

**Review by tianzhou — APPROVED** [review]
Welcome abroad ~

**Comment by candy2255** [comment]
Thanks! I am glad to be a part of Bytebase

**Pull request merged**
