### PR TITLE
docs: update CTA section

### PR DESCRIPTION
**Pull request by tianzhou**
Combine logo cloud with CT and use a bold style

CleanShot 2022-08-28 at 12 21 17

CleanShot 2022-08-28 at 12 22 18

Followup PRs will improve the other area to match the style

### CODE REVIEW

**Comment by tianzhou** [comment]
@adela-bytebase @candy2255 @changyuwong

**Comment by ecmadao** [comment]
Maybe need to change the layout on mobile?
图片

**Comment by tianzhou** [comment]
> Maybe need to change the layout on mobile? 图片

Done

CleanShot 2022-08-28 at 12 37 34

**Comment by tianzhou** [comment]
@ecmadao PTAL

**Review by ecmadao — APPROVED** [review]
LGTM

**Pull request merged**
