### PR TITLE
docs: update CODEOWNERS

### PR DESCRIPTION
**Pull request by d-bytebase**

### CODE REVIEW

**Review by boojack — APPROVED** [review]
LGTM

**Review by adela-bytebase — APPROVED** [review]
LGTM

**Review by boojack — COMMENTED** [review]
But why delete `assets/people/changyu.webp` in this PR.

**Comment by d-bytebase** [comment]
> But why delete `assets/people/changyu.webp` in this PR.

Good eye, I think that was a merge conflict. Done.

**Review by boojack — APPROVED** [review]
LGTM

**Review by adela-bytebase — APPROVED** [review]
LGTM

**Review by ecmadao — APPROVED** [review]
LGTM

**Pull request merged**
