### PR TITLE
chore: render markdown title manually

### PR DESCRIPTION
**Pull request by boojack**
Render markdown title manually to unify `changelog/blog` and `docs` display.

### CODE REVIEW

**Comment by d-bytebase** [comment]
@LiuJi-Jim PTAL

**Review by LiuJi-Jim — COMMENTED** [review]
LGTM otherwise

**Comment by boojack** [comment]
PTAL

**Review by d-bytebase — APPROVED** [review]

**Review by LiuJi-Jim — APPROVED** [review]
LGTM

**Pull request merged**
