### PR TITLE
docs: add DevJoy link

### PR DESCRIPTION
**Pull request by tianzhou**
Only show in Chinese version

CleanShot 2022-10-20 at 14 59 12

CleanShot 2022-10-20 at 14 59 55

### CODE REVIEW

**Comment by boojack** [comment]
image

It will cover a lot of area in mobile view. How about hiding the location and date strings in mobile view?

**Comment by tianzhou** [comment]
> image
> 
> It will cover a lot of area in mobile view. How about hiding the location and date strings in mobile view?

CleanShot 2022-10-20 at 15 11 31

**Review by boojack — APPROVED** [review]
LGTM

**Review by ecmadao — APPROVED** [review]
LGTM

**Pull request merged**
