### PR TITLE
feat: sticky header

### PR DESCRIPTION
**Pull request by boojack**
image

### CODE REVIEW

**Comment by tianzhou** [comment]
The existing header and the illustration are side-by-side, which is a deliberate design to make it look more special. Looks like this change changed that and put the header on the top.

I guess that's because we need to make the header sticky? If that's the case, I think it's a worthwhile trade-off.

Then, let's do some more improvement

1. Move the star-us button to the right-most
2. Center the header link (Docs, Blog, Pricing)
3. When header because sticky, are we able to display the "Deploy now in 5 seconds" and the "live demo" button on the right-most part of the header (to the right of the star-us button)?

**Comment by boojack** [comment]
> The existing header and the illustration are side-by-side, which is a deliberate design to make it look more special. Looks like this change changed that and put the header on the top.
> 
> I guess that's because we need to make the header sticky? If that's the case, I think it's a worthwhile trade-off.
> 
> Then, let's do some more improvement
> 
> 1. Move the star-us button to the right-most
> 2. Center the header link (Docs, Blog, Pricing)
> 3. When header because sticky, are we able to display the "Deploy now in 5 seconds" and the "live demo" button on the right-most part of the header (to the right of the star-us button)?

I put the header and banner together to make them in a sticky `div`. This will make header more semantic.

3. We can display these buttons in header when page scroll over them. And should we only display these buttons on other pages? e.g. /pricing page 
image

**Comment by tianzhou** [comment]
> > The existing header and the illustration are side-by-side, which is a deliberate design to make it look more special. Looks like this change changed that and put the header on the top.
> > I guess that's because we need to make the header sticky? If that's the case, I think it's a worthwhile trade-off.
> > Then, let's do some more improvement
> > 
> > 1. Move the star-us button to the right-most
> > 2. Center the header link (Docs, Blog, Pricing)
> > 3. When header because sticky, are we able to display the "Deploy now in 5 seconds" and the "live demo" button on the right-most part of the header (to the right of the star-us button)?
> 
> I put the header and banner together to make them in a sticky `div`. This will make header more semantic.
> 
> 3. We can display these buttons in header when page scroll over them. And should we display these buttons on other pages? e.g. /pricing page
> 
> image

/pricing page is actually a bit special since the primary action we want users to take is to make the purchase decision, thus having another primary action might diverge their attention. But that's just a guess. 

So to make things easy, we can blindly apply the sticky header to all pages for now

**Comment by boojack** [comment]
PTAL, change the demo page: [https://bytebase-com-pr-97.onrender.com/](https://bytebase-com-pr-97.onrender.com/)

**Comment by tianzhou** [comment]
I checked the demo, can we have the "deploy now" and "live demo button" on the sticky header for all pages. I only see it appears on the front page.

**Comment by boojack** [comment]
> I checked the demo, can we have the "deploy now" and "live demo button" on the sticky header for all pages. I only see it appears on the front page.

Of course if you want. Because other pages don't have these buttons in the content, I suggest that we should show it all the time in the header. wdyt

**Comment by tianzhou** [comment]
SGTM

**Comment by boojack** [comment]
PTAL

**Review by tianzhou — APPROVED** [review]
LGTM

**Pull request merged**
