### PR TITLE
docs: add how to add Git provider for GitHub.com

### PR DESCRIPTION
**Pull request by unknwon**
Fix BYT-991

### CODE REVIEW

**Comment by unknwon** [comment]
Page preview: https://bytebase-com-git-jc-github-com-docs-bytebase.vercel.app/docs/vcs-integration/add-git-provider

**Comment by d-bytebase** [comment]
@cla-bot check

**Review by tianzhou — APPROVED** [review]
LGTM

**Comment by d-bytebase** [comment]
@cla-bot check

**Review by d-bytebase — APPROVED** [review]

**Comment by d-bytebase** [comment]
@cla-bot check

**Comment by unknwon** [comment]
Merging as-is, happy to address any post-merge comments!

**Pull request merged**
