### PR TITLE
docs: update deploy to alicloud computenest docs

### PR DESCRIPTION
**Pull request by KunSir991**

### CODE REVIEW

**Comment by tianzhou** [comment]
https://www.bytebase.com/docs/get-started/self-host/#deploy-to-paas

You change is already live

**Comment by KunSir991** [comment]
image


> https://www.bytebase.com/docs/get-started/self-host/#deploy-to-paas
> 
> Your change is already live

image
但是官网文档中没看到应文档 这是啥原因呢

**Comment by tianzhou** [comment]
Oh, we updated the chinese version once every week. So the change will be delayed.

**Comment by KunSir991** [comment]
> Oh, we updated the chinese version once every week. So the change will be delayed.

明白了 那请把这个更新文档的PR也合并下  感谢

**Pull request closed without merging**
