### PR TITLE
feat: overview page unclickable

### PR DESCRIPTION
**Pull request by boojack**
* Add `hide` field to make doc unclickable into `.md` fields;
* Add `description` field to dynamic generate page metadata. And it's optional right now(I just write two example description for "/docs/what-is-bytebase" and "/docs/document-write-guide", maybe @bytebase/bytebase-devrel could help finish this). If it is null, this field would be a slice string of document content.

### CODE REVIEW

**Review by tianzhou — COMMENTED** [review]
How about call "header" instead of "hide" ?

**Comment by boojack** [comment]
> How about call "header" instead of "hide" ?

Maybe `isHeader: boolean` is better. I really don't the meaning of `header` in first sight. wdyt

**Comment by tianzhou** [comment]
> > How about call "header" instead of "hide" ?
> 
> Maybe `isHeader: boolean` is better. I really don't know the meaning of `header` in first sight. wdyt

SGTM

**Comment by boojack** [comment]
PTAL

**Review by tianzhou — APPROVED** [review]
LGTM

**Pull request merged**
